# Site settings
title: Dr Matthew P. Humphreys
description: >- # this means to ignore newlines until "baseurl:"
  Seawater biogeochemistry, scientific programming, and the marine carbon&nbsp;cycle
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://mvdh.xyz" # the base hostname & protocol for your site, e.g. http://example.com
repository: mvdh7/mvdh7.github.io

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


### Navbar Settings ###
nav_exclude:  # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

# Author Info
author:
  name: Matthew P. Humphreys
  image: https://raw.githubusercontent.com/mvdh7/mvdh7.github.io/master/images/fallowfields.jpg
  email: m.p.humphreys@icloud.com
  github: mvdh7
  twitter: matthew_vdh
  linkedin: matthew-p-humphreys-4745833a
#  facebook : username

# Collections
collections:
  projects:
    output: true
    permalink: /research/:name

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false  # Set to true to enable disqus comments

# Posts default Permalink
permalink: blog/:title

# Exclude from processing.
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - _posts/inprep/*
  - _projects/snippets.md
