### Site Settings ###
title               : Dr Matthew P. Humphreys
description         : >-
                      Seawater biogeochemistry, scientific&nbsp;programming, and the&nbsp;marine&nbsp;carbon&nbsp;cycle
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url: "https://mvdh.xyz" # the base hostname & protocol for your site, e.g. http://example.com
repository          : mvdh7/mvdh7.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Matthew P. Humphreys
  image             : https://raw.githubusercontent.com/mvdh7/mvdh7.github.io/master/images/fallowfields.jpg
  # behance           : your_username
# dribbble          : your_username
  email             : m.p.humphreys@icloud.com
  # facebook          : your_username
  github            : mvdh7
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : matthew-p-humphreys-4745833a
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : matthew_vdh
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /research/:name
  code:
    output: true
    permalink: /code/:name


### Disqus ###
# disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "code"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - original
  - _posts/inprep/*
  - _projects/snippets.md
