# Site settings
title: Dr Matthew P. Humphreys
description: >- # this means to ignore newlines until "baseurl:"
  Seawater biogeochemistry, scientific programming, and the marine carbon&nbsp;cycle
baseurl: "/"  # the subpath of your site, e.g. /blog
url: "https://mvdh7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: mvdh7/mvdh7.github.io


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Matthew P. Humphreys
  image    : https://raw.githubusercontent.com/mvdh7/mvdh7.github.io/master/images/fallowfields.jpg
  email    : m.humphs@gmail.com
  github   : mvdh7
  twitter  : matthew_vdh
  linkedin : matthew-p-humphreys-4745833a
#  facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
